# A name for our Workflow
name: Build and Deploy React App

# Specifies that the workflow should be triggered on a Git push event.
on:
  push:
    branches:
      #Specifies the branches on which the workflow should be triggered
      - main
#Defines the jobs to be executed as part of the workflow
jobs:
  #The name of the job, in this case, "CI-CD."
  CI-CD:
    runs-on: ubuntu-latest
    #Lists the individual steps to be executed within the job.
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      #Sets up Node.js on the runner using the `actions/setup-node@v3` GitHub Action. It specifies that Node.js version 16 should be used.
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        # Allows passing additional parameters to the action, in this case, specifying the Node.js version.
        with:
          node-version: 20
      #Installs project dependencies using the `npm install` command.
      - name: Install Dependencies
        run: npm install
      #Builds the React app using the `npm run build` command.
      - name: Build React App
        run: npm run build
      #Adds an SSH private key to the SSH agent
      - name: Add SSH Key to Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #Performs the actual deployment.
      #It consists of a multi-line script (run:) Prints the current working directory and lists its contents.
      #Outputs a message indicating the start of the deployment.
      #Use SSH to connect to the CentOS 7 server (${{ secrets.SSH_HOST }}) with the specified port, user, and private key. It then changes to the deployment directory (/usr/share/nginx/portfolio/build), removes existing contents, and exits.
      #Use scp to securely copy the contents of the local ./build/* directory to the specified deployment directory on the server.
      #Outputs a message indicating the completion of the deployment.
      # - name: Deploy React App to Linux
      #   run: |
      #     echo "Current Working Directory: $(pwd)"
      #     echo "Contents of the directory: $(ls -la)"
      #     echo "Starting deployment....."
      #     ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /usr/share/nginx/portfolio/build && rm -rf * && exit"
      #     scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} -r ./build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/usr/share/nginx/portfolio/build
      #     echo "Deployment completed."
      - name: Deploy to server via SSH
      env:
        SERVER_IP: ${{ secrets.SSH_HOST }}
        SERVER_USERNAME: ${{ secrets.SSH_USER }}
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./build/ ${{ env.SERVER_USERNAME }}@${{ env.SERVER_IP }}:/root/demo-build # Adjust the path on the server as needed
