name: Deploy React Project

on:
  push:
    branches:
      - main  # Deploy when pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    - name: Verify Build Directory
      run: ls -la ./build  # List the contents of the build directory to check if it exists

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATEKEY }}

    - name: Deploy to server via SSH
      if: success()
      env:
        SERVER_IP: ${{ secrets.SSH_HOST }}
        SERVER_USERNAME: ${{ secrets.SSH_USER }}
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./build/ ${{ env.SERVER_USERNAME }}@${{ env.SERVER_IP }}:/var/www/htnk # Adjust the path on the server as needed
